### PR TITLE
Add gitignore

### PR DESCRIPTION
**Pull request by Artforlfmj**
Add gitignore to prevent node modules and sensitive data to be sent

### CODE REVIEW

**Review by theo-bnts — CHANGES_REQUESTED** [review]

**Review by theo-bnts — CHANGES_REQUESTED** [review]
You should remove empty lines, add `database-template.sql`, and `readme.md`.
Thanks for your contribution.

**Review by theo-bnts — CHANGES_REQUESTED** [review]
Could you just remove the empty line, please ?

**Comment by Artforlfmj** [comment]
it was removed. lemme push it

**Review by theo-bnts — APPROVED** [review]

**Comment by Artforlfmj** [comment]
there you go

**Pull request merged**
